// Code generated by protoc-gen-gogo.
// source: dataaccess.proto
// DO NOT EDIT!

/*
Package dataaccess is a generated protocol buffer package.

It is generated from these files:
	dataaccess.proto

It has these top-level messages:
*/
package dataaccess

import proto "github.com/gogo/protobuf/proto"
import fmt "fmt"
import math "math"
import google_protobuf "github.com/gogo/protobuf/protoc-gen-gogo/descriptor"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

var E_Model = &proto.ExtensionDesc{
	ExtendedType:  (*google_protobuf.MessageOptions)(nil),
	ExtensionType: (*bool)(nil),
	Field:         66001,
	Name:          "dataaccess.model",
	Tag:           "varint,66001,opt,name=model",
}

var E_Primarykey = &proto.ExtensionDesc{
	ExtendedType:  (*google_protobuf.FieldOptions)(nil),
	ExtensionType: (*bool)(nil),
	Field:         66001,
	Name:          "dataaccess.primarykey",
	Tag:           "varint,66001,opt,name=primarykey",
}

func init() {
	proto.RegisterExtension(E_Model)
	proto.RegisterExtension(E_Primarykey)
}
